# promptのカラーを設定しています、$変数は後述で設定している変数が差し込まれます
format = """
$directory\
[](fg:#6b4f9f bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$fill\
$kubernetes\
$time\
\n$character"""

right_format = """$cmd_duration"""

add_newline = true

[os]
format = "[$symbol]($style)"
style = "fg:#FFFFFF bg:#6b4f9f bold"
disabled = false

[os.symbols]
Macos = "  " # nf-fa-apple
Ubuntu = "  " # nf-linux-ubuntu
Debian = "  " # nf-linux-debian

[directory]
style = "fg:#FFFFFF bg:#6b4f9f bold"
format = "[ $path ]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#9d7cd8 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#9d7cd8 bg:#394260)]($style)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[$duration]($style) "

[kubernetes]
disabled = false
style = "fg:#ffffff bg:#1d2230"
format = '[](fg:#1d2230)[ ⎈ $context ]($style)[](fg:#1d2230)'

[[kubernetes.contexts]]
context_pattern = ".*prod.*"
style = "fg:#cc3333 bg:#1d2230"

[[kubernetes.contexts]]
context_pattern = ".*dev.*"
style = "fg:#ae8b2d bg:#1d2230"

[fill]
symbol = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
